// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByAuthenticationID = `-- name: GetUserByAuthenticationID :one
SELECT "id", "agentId"
FROM "user"
WHERE "authenticationID" = $1
`

type GetUserByAuthenticationIDRow struct {
	ID      pgtype.UUID
	AgentId pgtype.UUID
}

func (q *Queries) GetUserByAuthenticationID(ctx context.Context, authenticationid pgtype.UUID) (GetUserByAuthenticationIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthenticationID, authenticationid)
	var i GetUserByAuthenticationIDRow
	err := row.Scan(&i.ID, &i.AgentId)
	return i, err
}
