// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByAuthenticationID = `-- name: GetUserByAuthenticationID :one
SELECT "id"
FROM "user"
WHERE "authenticationID" = $1
`

func (q *Queries) GetUserByAuthenticationID(ctx context.Context, authenticationid pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByAuthenticationID, authenticationid)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
