apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-service-config
  labels:
    app.kubernetes.io/name: oidc-service
    app.kubernetes.io/part-of: alkemio-platform
data:
  OIDC_HYDRA_ADMIN_URL: https://hydra-admin.example
  OIDC_KRATOS_ADMIN_URL: https://kratos-admin.example
  OIDC_ALLOW_INSECURE_HTTP: "false"
  OIDC_MAINTENANCE_MODE: "false"
  OIDC_MAINTENANCE_RETRY: "0"
  OIDC_READINESS_TIMEOUT: 5s
  OIDC_LOG_LEVEL: info
